apiVersion: apps/v1
kind: Deployment
metadata:
  name: class-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: class-service
  template:
    metadata:
      labels:
        app: class-service
    spec:
      containers:
      - name: class-service
        image: yodh4/class-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: postgresql+asyncpg://postgres:postgres@class-postgres:5432/class_service_db
        - name: JWT_SECRET
          value: EfEmEitch123
        - name: ATTENDEE_SERVICE_URL
          value: http://18.214.134.23:8000
---
apiVersion: v1
kind: Service
metadata:
  name: class-service
spec:
  selector:
    app: class-service
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
